AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Exclude: ["**/*_spec.rb"]

Lint/MissingSuper:
  Enabled: false

Lint/ConstantDefinitionInBlock:
  Exclude: ["**/*_spec.rb"]

